### ISSUE TITLE
[Maven] Erreur de compilation dans le projet avec `mvn clean install`

### ISSUE THREAD

**Issue by JFLeblay** [mgl805-aut24-equipe-3/Test-Automation-Framework#3]
L'erreur est sur la classe entity.User:
![image](https://github.com/user-attachments/assets/53f16290-f626-4a7e-9b0e-acaf9de11aab)
![image](https://github.com/user-attachments/assets/a396c29f-7144-4ca4-8f43-ea8c700b83f6)
![image](https://github.com/user-attachments/assets/e0c322a0-57c4-4f84-a6f1-8d077448c01c)

**Comment by JFLeblay** [comment]
@alexnezami Merci de continuer sur GitHub pour pouvoir documenter la résolution

**Comment by alexnezami** [comment]
[maven.log](https://github.com/user-attachments/files/17193300/maven.log)


Description du problème :

	1.	Erreurs “cannot find symbol” :
	•	Plusieurs méthodes ne sont pas reconnues par le compilateur Java. Ces méthodes incluent : setRoles, getRoles, getId, getFullName, et d’autres.
	•	Cela signifie que la classe User n’a pas les méthodes attendues définies, ou que le code qui utilise ces méthodes n’a pas la bonne version de la classe User.
	2.	Utilisation d’une API dépréciée :
	•	Le fichier JMeterRunner.java utilise une API qui est dépréciée (ancienne et qui peut ne plus être supportée dans le futur).

Ce que cela signifie :

	•	Le compilateur Java ne parvient pas à trouver les méthodes spécifiées dans la classe User. Cela peut être dû à des problèmes de définition de cette classe ou à un import incorrect des dépendances.
	•	Le message concernant Recompile with -Xlint:deprecation for details signifie que la classe JMeterRunner.java utilise des fonctionnalités obsolètes et qu’il serait préférable de les mettre à jour.

Recommandations :

	1.	Vérifiez la classe User :
	•	Assurez-vous que la classe User contient bien toutes les méthodes qui sont référencées, telles que getRoles(), setRoles(Set<Role>), etc.
	•	Vérifiez les importations de la classe User pour vous assurer qu’elle provient du bon package.
	2.	Mettre à jour le code déprécié :
	•	Exécutez la compilation avec l’option -Xlint:deprecation pour obtenir plus d’informations sur les méthodes obsolètes et les mettre à jour.

**Comment by JFLeblay** [comment]
@alexnezami Peux-tu installer le JDK 17? Ta trace Maven montre que tu utilises 23.
Je te conseille [SDKMan](https://sdkman.io/) pour gérer les différentes versions de Java sur ton Mac.

**Comment by JFLeblay** [comment]
@alexnezami Le projet utilise [annotations lombok](https://projectlombok.org/) pour générer du code. Par exemple, dans la classe User.java tu ne verras les méthodes qui posent problèmes car les getters et setters sont générés par Lombok. Dans le source, tu vois `@Getter` et `@Setter` qui sont transformé à la compilation par des vrais getters et setters le fichier User.class.

Upload ton fichier User.class que tu trouveras dans `backend/target/classes/ca/etsmtl/taf/entity/` pour que je vois c'est quoi le code généré. @alexnezami

**Comment by J-Champagne** [comment]
@JFLeblay pourrais-tu nous partager la version exacte de Java que tu utilises?
J'essai de télécharger la version 17 à travers SDKMAN sans succès, j'ai toujours l'erreur :
`Stop! 17.0.12-jbr is not a valid candidate.`

Aussi, peux-tu nous confirmer que tu utilises ton mac avec un processeur ARM pour rouler le logiciel, sans VM?

**Comment by JFLeblay** [comment]
@J-Champagne Je roule la version `17.0.12-sapmchn`. J'ai un mac ARM (M3 Pro). Est-ce que tu roules la commande `sdk install java <candidte>`

**Comment by J-Champagne** [comment]
J'ai réussi à compiler! Je crois qu'il faut absolument utiliser la version 17

<img width="827" alt="Screenshot 2024-09-30 at 2 10 13 PM" src="https://github.com/user-attachments/assets/51f0774a-858e-46ae-868e-60cdb2662ec8">

**Comment by JFLeblay** [comment]
@alexnezami @J-Champagne Je pense que j'ai trouvé la cause de votre prob: https://github.com/projectlombok/lombok/issues/3722#issue-2463299849

Installer la version 17 est la solution pour l'instant.

**Comment by alexnezami** [comment]
![Screenshot 2024-09-30 at 17 10 31](https://github.com/user-attachments/assets/223fa29d-164b-4c7a-9547-b24eedbcfa21)
Et voilà ça marche pour moi aussi, donc pour moi le problème c’était autre chose parce que java pour moi c’était installé sur machine virtuelle et donc le projet n'a pas détecté jdk sur ma machine
Merci à tous et Bonne continuation
